name: very_good_app
description: An example app build with very_good_cli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_launcher_icons:
    path: ../..

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"


